package com.cyclo.zvxgw008_srv_entities.v1.helpers;
/*

 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1

*/
import java.util.ArrayList;
import java.util.List;

/**
 * A wrapper class for the listeners of request handler.
 */
public class ListenerWrapper
{
    // the listener
    private IZVXGW008_SRV_EntitiesRequestHandlerListener listener;
    // the list of request IDs
    private List<ZVXGW008_SRV_EntitiesRequestID> requestIDs;
    
    /**
     * Constructs a new listener wrapper with the given listener
     * and request IDs.
     * 
     * @param listener - the request handler listener.
     * @param requestIDs - may be passed as an array or as a sequence of request IDs.
     */
    public ListenerWrapper(IZVXGW008_SRV_EntitiesRequestHandlerListener listener, ZVXGW008_SRV_EntitiesRequestID... requestIDs)
    {
        this.listener = listener;
        
        this.requestIDs = new ArrayList<ZVXGW008_SRV_EntitiesRequestID>();
        for (ZVXGW008_SRV_EntitiesRequestID requestID : requestIDs)
        {
            this.requestIDs.add(requestID);
        }
    }

    /**
     * Returns the listener.
     * @return the listener.
     */
    public IZVXGW008_SRV_EntitiesRequestHandlerListener getListener()
    {
        return listener;
    }

    /**
     * Returns the request IDs.
     * @return - the request IDs.
     */
    public List<ZVXGW008_SRV_EntitiesRequestID> getRequestIDs()
    {
        return requestIDs;
    }
}