package com.cyclo.zvxgw008_srv_entities.v1.helpers;
/*

 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1

*/
 /**
  * Enum that represents all request IDs.
  */
public enum ZVXGW008_SRV_EntitiesRequestID 
{
		LOAD_CUSTOMERSET_ENTRY,
		LOAD_MATERIALSET_ENTRY,
		LOAD_CUSTOMERSET,
		LOAD_MATERIALSET
}
